// Code generated by kueinit. DO NOT EDIT.
package modules

import (
	di "github.com/kuetix/container"
	"github.com/kuetix/engine/engine/defines"
	"github.com/kuetix/engine/engine/workflow"
	transitionsConverse "github.com/kuetix/std-core/modules/converse/transitions"
	transitionsServicesCommon "github.com/kuetix/std-core/modules/services/common/transitions"
)

func init() {
	di.Boot()
	di.DependencyInjection["converse"] = func(name string) {
		di.ToResolve(defines.TransitionPrefix+"converse"+"/"+"speak", func() interface{} { return workflow.ServiceTransitionMapping{ ServiceName: name, Name: "speak", Impl: transitionsConverse.NewSpeakTransitions() }})
	}
	di.DependencyInjection["services/common"] = func(name string) {
		di.ToResolve(defines.TransitionPrefix+"services/common"+"/"+"assert", func() interface{} { return workflow.ServiceTransitionMapping{ ServiceName: name, Name: "assert", Impl: transitionsServicesCommon.NewAssertTransitions() }})
		di.ToResolve(defines.TransitionPrefix+"services/common"+"/"+"context", func() interface{} { return workflow.ServiceTransitionMapping{ ServiceName: name, Name: "context", Impl: transitionsServicesCommon.NewContextTransitions() }})
		di.ToResolve(defines.TransitionPrefix+"services/common"+"/"+"datetimeAt", func() interface{} { return workflow.ServiceTransitionMapping{ ServiceName: name, Name: "datetimeAt", Impl: transitionsServicesCommon.NewDatetimeAtTransitions() }})
		di.ToResolve(defines.TransitionPrefix+"services/common"+"/"+"debug", func() interface{} { return workflow.ServiceTransitionMapping{ ServiceName: name, Name: "debug", Impl: transitionsServicesCommon.NewDebugTransitions() }})
		di.ToResolve(defines.TransitionPrefix+"services/common"+"/"+"entity", func() interface{} { return workflow.ServiceTransitionMapping{ ServiceName: name, Name: "entity", Impl: transitionsServicesCommon.NewEntityTransitions() }})
		di.ToResolve(defines.TransitionPrefix+"services/common"+"/"+"errors", func() interface{} { return workflow.ServiceTransitionMapping{ ServiceName: name, Name: "errors", Impl: transitionsServicesCommon.NewErrorsTransitions() }})
		di.ToResolve(defines.TransitionPrefix+"services/common"+"/"+"log", func() interface{} { return workflow.ServiceTransitionMapping{ ServiceName: name, Name: "log", Impl: transitionsServicesCommon.NewLogTransitions() }})
		di.ToResolve(defines.TransitionPrefix+"services/common"+"/"+"orchestration", func() interface{} { return workflow.ServiceTransitionMapping{ ServiceName: name, Name: "orchestration", Impl: transitionsServicesCommon.NewOrchestrationTransitions() }})
		di.ToResolve(defines.TransitionPrefix+"services/common"+"/"+"pagination", func() interface{} { return workflow.ServiceTransitionMapping{ ServiceName: name, Name: "pagination", Impl: transitionsServicesCommon.NewPaginationTransitions() }})
		di.ToResolve(defines.TransitionPrefix+"services/common"+"/"+"response", func() interface{} { return workflow.ServiceTransitionMapping{ ServiceName: name, Name: "response", Impl: transitionsServicesCommon.NewResponseTransitions() }})
		di.ToResolve(defines.TransitionPrefix+"services/common"+"/"+"workflow", func() interface{} { return workflow.ServiceTransitionMapping{ ServiceName: name, Name: "workflow", Impl: transitionsServicesCommon.NewWorkflowTransitions() }})
	}
}
